steps:
  - name: "gcr.io/cloud-builders/npm"
    dir: "frontend"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    dir: "frontend"
    args: ["run", "build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: [
      "-c",
      "gcloud app deploy frontend/app.yaml --quiet"
    ]
timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
